services:
  user:
    build: ./user_service
    container_name: user_service
    ports:
      - "8002:8000"
    depends_on:
      - mysql_db

  product:
    build: ./product_service
    container_name: product_service
    ports:
      - "8001:8000"
    depends_on:
      - mongo_db

  cart:
    build: ./cart_service
    container_name: cart_service
    ports:
      - "8003:8000"
    depends_on:
      - mysql_db

  order:
    build: ./order_service
    container_name: order_service
    ports:
      - "8005:8000"
    depends_on:
      - postgres_db

  payment:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "8007:8000"
    depends_on:
      - postgres_db

  shipment:
    build: ./shipment_service
    container_name: shipment_service
    ports:
      - "8006:8000"
    depends_on:
      - postgres_db

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
